# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MChanger.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Result1 import Ui_MainWindow as rst
from PyQt5.QtWidgets import QMessageBox
import sys

class Ui_MainWindow(object):

    def __init__(self):
        self.NewDialog = QtWidgets.QMainWindow()
        self.New_secren = rst()
        self.New_secren.setupUi(self.NewDialog)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 537)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Forte")
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(250, 0, 250, 173)
        self.verticalLayout_2.setSpacing(50)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 697, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.pushButton.clicked.connect(self.resultWindow)
        self.New_secren.btn_exit.clicked.connect(self.ext)
        self.New_secren.btn_reset.clicked.connect(self.rst)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Money Changer"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Enter Amount"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
        self.pushButton.setShortcut(_translate("MainWindow", "Return"))

    def calculater(self,money):
        if money % 10 == 0:
            return money // 10, 0, 0, 0
        elif money % 5 == 0:
            return money // 10, (money % 10) // 5, 0, 0
        elif money < 5 and money % 2 == 0:
            return 0, 0, money // 2, 0
        elif money == 3:
            return 0, 0, 1, 1
        elif money == 1:
            return 0, 0, 0, 1
        else:
            ten = money // 10
            five = ((money) - ten * 10) // 5
            two = ((money) - (ten * 10) - five * 5) // 2
            one = ((money) - (ten * 10) - (five * 5) - two * 2)
            return ten, five, two, one

    def resultWindow(self):
        money = self.lineEdit.text()
        try:
            money = int(money)
        except:
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Information)
            msg.setWindowTitle("Invalid amount")
            msg.setText("Please enter a valid amount")
            msg.exec_()
            return

        if money == 0:
            massage = QMessageBox()
            massage.setIcon(QMessageBox.Information)
            massage.setWindowTitle("Invalid amount")
            massage.setText("Please enter a valid amount")
            massage.exec_()
            return

        self.openResultWindow(money)

    def openResultWindow(self,money):
        self.NewDialog.show()
        ten,five,two,one=self.calculater(money)
        # print(ten,five,two,one)
        self.New_secren.tableWidget.item(0,0).setText(str(one))
        self.New_secren.tableWidget.item(1,0).setText(str(two))
        self.New_secren.tableWidget.item(2,0).setText(str(five))
        self.New_secren.tableWidget.item(3,0).setText(str(ten))
        self.New_secren.tableWidget.item(4,0).setText(str(one+two+five+ten))
        self.New_secren.tableWidget.item(0,1).setText(str(one*1))
        self.New_secren.tableWidget.item(1,1).setText(str(two*2))
        self.New_secren.tableWidget.item(2,1).setText(str(five*5))
        self.New_secren.tableWidget.item(3,1).setText(str(ten*10))
        self.New_secren.tableWidget.item(4,1).setText(str((one*1)+(two*2)+(five*5)+(ten*10)))

    def ext(self):
        sys.exit(app.exec_())

    def rst(self):
        self.NewDialog.close()
        self.lineEdit.clear()
        pass

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
